# BTC LTP Service - Configuración Base
# Esta configuración se puede override con variables de entorno o archivos específicos del entorno

# Configuración del servidor HTTP
server:
  port: 8080
  shutdown_timeout: 30s

# Configuración del sistema de cache
cache:
  backend: memory  # Options: memory, redis
  ttl: 30s
  redis:
    addr: localhost:6379
    password: ""
    db: 0

# Configuración de exchanges de criptomonedas
exchange:
  kraken:
    rest_url: https://api.kraken.com/0/public
    websocket_url: wss://ws.kraken.com
    timeout: 10s
    request_timeout: 3s
    fallback_timeout: 5s
    max_retries: 3

# Configuración de rate limiting
rate_limit:
  enabled: true
  capacity: 100    # requests per bucket
  refill_rate: 10  # requests per second refill

# Configuración del sistema de logging
logging:
  level: info      # Options: debug, info, warn, error
  format: json     # Options: json, text

# Configuraciones de negocio específicas
business:
  supported_pairs: 
    - "BTC/USD"
    - "ETH/USD" 
    - "LTC/USD"
    - "XRP/USD"
    - "BTC/EUR"
    - "ETH/EUR"
  cache_prefix: "price:"
